services:
    _defaults:
        autowire: true
        autoconfigure: true

    Qbbr\LocaleConfiguratorBundle\Configurator\LocaleConfigurator:
        arguments:
            $configDir: '%qbbr.locale_configurator.config_dir%'
            $raiseNotFoundParamException: '%qbbr.locale_configurator.raise_not_found_param_exception%'

