name: Tests

on: [push]

jobs:
  test:
    name: Run Symfony Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: composer, symfony
      - name: Depends install
        run: composer install
      - name: Check
        run: |
          composer check
          symfony check:security
      - name: Run tests
        run: ./vendor/bin/phpunit Tests/ -v --testdox
